name: compile-and-test-C-program

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: install gcc
        run: sudo apt-get install -y ${{ matrix.compiler }}

      - name: compile C source code
        run: ${{ matrix.compiler }} -o hello_world.exe hello.c

      - name: Run tests
        run: |
          if ./hello_world.exe; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi

      - name: Upload compiled code
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.compiler }}_hello_world.exe
          path: hello_world.exe
